name: Phpcs

on:
 push:
   branches:
     - main

jobs:
 phpcs:
   runs-on: ubuntu-latest
   services:
     mysql:
       image: mysql:8.0
       env:
         MYSQL_DATABASE: news-aggregator
         MYSQL_USER: news-aggregator
         MYSQL_PASSWORD: secret
         MYSQL_ROOT_PASSWORD: secret
       ports:
         - 3306:3306
       options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

     redis:
       image: redis
       ports:
         - 6379:6379
       options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3

   steps:
     - name: Checkout
       uses: actions/checkout@v2

     - name: Setup PHP
       uses: shivammathur/setup-php@v2
       with:
         php-version: '8.3'
         coverage: none
         tools: composer, cs2pr

     - name: Get Composer cache directory
       id: composer-cache
       run: echo "::set-output name=dir::$(composer config cache-files-dir)"

     - name: Setup cache
       uses: pat-s/always-upload-cache@v1.1.4
       with:
         path: ${{ steps.composer-cache.outputs.dir }}
         key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
         restore-keys: ${{ runner.os }}-composer-

     - name: Create .env file
       run: cp .env.example .env

     - name: Install dependencies
       run: composer install --prefer-dist --no-suggest --no-progress

     - name: Detect coding standard violations
       run: composer cs-check && composer phpstan
